---
# Cirrus CI configuration for testing MacbookSetup on Apple Silicon macOS

# Environment variables for the entire workflow
env:
  # Set non-interactive mode for Homebrew to avoid prompts
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_ENV_HINTS: 1
  # Avoid prompts during script execution
  CI: true
  NONINTERACTIVE: 1

# Daily scheduled validation build
# This task runs every day at midnight UTC to ensure ongoing compatibility
# with the latest macOS updates and Homebrew formula changes
daily_validation_task:
  name: daily_compatibility_check
  trigger_type: scheduled
  cron: "0 0 * * *"  # Run at midnight UTC every day
  
  # Use macOS Ventura on Apple Silicon
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
    cpu: 4
    memory: 8G
  
  # Set a timeout for the entire task (3 hours)
  timeout_in: 180m
  
  # Clone the repository
  clone_script:
    - git clone $CIRRUS_REPO_CLONE_URL .
  
  # Generate CI setup script by patching the original setup.sh
  prepare_script:
    - |
      # Source the CI modifiers
      source ci_modifiers.sh
      
      # Generate the CI setup script from the original setup.sh
      patch_for_ci setup.sh ci_setup.sh
      
      # Verify the script was created successfully
      if [[ ! -f ci_setup.sh ]]; then
        echo "Failed to generate CI setup script"
        exit 1
      fi
      
  # Create a test script to verify installations
  create_test_script:
    - cp verify_setup.sh.template verify_setup.sh
    - chmod +x verify_setup.sh
  
  # Run the actual setup
  setup_script:
    - ./ci_setup.sh

  # Verify the installation
  verify_script:
    - zsh ./verify_setup.sh
  
  # Always collect logs for debugging
  always:
    logs_artifacts:
      path: "*.log"
      type: text/plain

# Task for testing the setup script on macOS ARM
macos_arm_test_task:
  # Use macOS Ventura on Apple Silicon
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
    cpu: 4
    memory: 8G
  
  # Set a timeout for the entire task (3 hours)
  timeout_in: 180m
  
  # Clone the repository
  clone_script:
    - git clone $CIRRUS_REPO_CLONE_URL .
  
  # Generate CI setup script by patching the original setup.sh
  prepare_script:
    - |
      # Source the CI modifiers
      source ci_modifiers.sh
      
      # Generate the CI setup script from the original setup.sh
      patch_for_ci setup.sh ci_setup.sh
      
      # Verify the script was created successfully
      if [[ ! -f ci_setup.sh ]]; then
        echo "Failed to generate CI setup script"
        exit 1
      fi
      
  # Create a test script to verify installations
  create_test_script:
    - cp verify_setup.sh.template verify_setup.sh
    - chmod +x verify_setup.sh
  
  # Run the actual setup
  setup_script:
    - ./ci_setup.sh

  # Verify the installation
  verify_script:
    - zsh ./verify_setup.sh
  
  # Always collect logs for debugging
  always:
    logs_artifacts:
      path: "*.log"
      type: text/plain

