repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [
          "--shell=bash",
          "--external-sources",
          "--source-path=SCRIPTDIR",
          "--exclude=SC1091,SC2296,SC2034,SC2154,SC2016"
        ]
        files: \.sh$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yaml"]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args: [
          "--shell=bash",
          "--external-sources",
          "--source-path=SCRIPTDIR",
          "--exclude=SC1091,SC2296,SC2034,SC2154,SC2016"
        ]
      - id: shfmt
        args: ["-i", "2", "-ci", "-bn", "-sr"] 