---
version: 2.1

# Define reusable commands
commands:
  install_homebrew:
    description: "Install Homebrew if not present"
    steps:
      - run:
          name: Install Homebrew
          shell: /bin/zsh
          command: |
            if ! command -v brew &>/dev/null; then
              # Set CI-specific Homebrew environment variables to prevent network issues
              export HOMEBREW_NO_AUTO_UPDATE=1
              export HOMEBREW_NO_INSTALL_CLEANUP=1
              export HOMEBREW_NO_ENV_HINTS=1
              export HOMEBREW_NO_ANALYTICS=1

              # Install Homebrew
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              [[ "$(uname -m)" == "arm64" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

              # Clean up problematic taps that might cause issues in CI
              brew untap homebrew/homebrew-cask-versions 2>/dev/null || true

              # Verify brew is working without forcing updates
              brew --version
            fi

  prepare_environment:
    description: "Prepare the CI environment"
    steps:
      - run:
          name: Install required tools and setup environment
          shell: /bin/zsh
          command: |
            # Install required tools (with CI protections)
            export HOMEBREW_NO_AUTO_UPDATE=1
            export HOMEBREW_NO_INSTALL_CLEANUP=1
            export HOMEBREW_NO_ENV_HINTS=1
            export HOMEBREW_NO_ANALYTICS=1
            export GIT_TERMINAL_PROMPT=0

            # Install shellcheck (skip if already installed to avoid update issues)
            if ! command -v shellcheck &>/dev/null; then
              brew install shellcheck
            else
              echo "shellcheck already installed, skipping to avoid update issues"
            fi

            # Set up environment variables consistently
            export ZDOTDIR="${HOME}"
            export ANTIDOTE_HOME="${HOME}/.antidote"

            # Create necessary directories first
            mkdir -p "${ZDOTDIR}"
            mkdir -p "${ANTIDOTE_HOME}"

            # Create .zsh_plugins.txt in the correct location
            if [[ ! -f "${ZDOTDIR}/.zsh_plugins.txt" ]]; then
                echo "Creating .zsh_plugins.txt in ${ZDOTDIR}"
                cat > "${ZDOTDIR}/.zsh_plugins.txt" \<< 'PLUGINS_EOF'
            # Core functionality
            zsh-users/zsh-completions
            zsh-users/zsh-autosuggestions
            zsh-users/zsh-syntax-highlighting

            # Git integration
            ohmyzsh/ohmyzsh path:plugins/git

            # Kubernetes tools
            ohmyzsh/ohmyzsh path:plugins/kubectl
            PLUGINS_EOF
                echo "Created .zsh_plugins.txt successfully"
            fi

            # Make scripts executable
            chmod +x setup.sh
            chmod +x verify_setup.sh

  run_setup:
    description: "Run the setup script"
    steps:
      - run:
          name: Run setup script
          shell: /bin/zsh
          command: zsh ./setup.sh 2>&1 | tee /tmp/circleci-build.log

  run_verification:
    description: "Run the verification script"
    steps:
      - run:
          name: Run verification script
          shell: /bin/zsh
          command: |
            source ~/.zshrc
            ./verify_setup.sh 2>&1 | tee verify.log

# Define the main workflow
workflows:
  version: 2
  build_and_test:
    jobs:
      - macos_test

# Define the macOS test job
jobs:
  macos_test:
    macos:
      xcode: "14.3.0"  # Specify the Xcode version
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_ENV_HINTS: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSECURE_REDIRECT: 1
      GIT_TERMINAL_PROMPT: 0
      CI: true
      NONINTERACTIVE: 1
      PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
      SHELL: /bin/zsh
      ZDOTDIR: $HOME
    steps:
      - checkout
      - install_homebrew
      - prepare_environment
      - run_setup
      - store_artifacts:
          path: /tmp/brew_bundle.log
          destination: brew_bundle_log
      - run_verification
      - store_artifacts:
          path: ~/.zshrc
          destination: zshrc
      - store_artifacts:
          path: ~/.zsh_plugins.txt
          destination: zsh_plugins
      - store_artifacts:
          path: verify.log
          destination: verify_log
      - store_artifacts:
          path: /tmp/circleci-build.log
          destination: build_log
          # Colima logs removed - no longer using containerization in CI
