name: ShellSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellSpec
        run: |
          curl -fsSL https://git.io/shellspec | sh -s -- --yes
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ShellSpec tests
        run: |
          shellspec spec/mcp_manager_spec.sh --format documentation
        env:
          CI: "true"
          GITHUB_PERSONAL_ACCESS_TOKEN: "test_token"
          CIRCLECI_TOKEN: "test_token"
